apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: adventurewords-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: adventurewords
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http         # must match the 'name' in Service
      interval: 15s
      path: /actuator/prometheus
      scheme: http
