apiVersion: v1
kind: Service
metadata:
  name: adventurewords-service
spec:
  type: NodePort
  selector:
    app: adventurewords
  ports:
    - protocol: TCP
      port: 8081        # portul expus intern în cluster
      targetPort: 8081  # portul aplicației din container
      nodePort: 30008   # un port liber între 30000-32767
